apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  labels:
    app: movie-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      # Init container waits for movie-db to be ready
      initContainers:
      - name: wait-for-movie-db
        image: busybox
        command:
          - sh
          - -c
          - |
            echo "Waiting for movie-db..."
            until nc -z movie-db 5432; do
              sleep 2
            done
            echo "Movie DB ready"

      containers:
      - name: movie-service
        image: ahmedmoussa92/movie-service:latest
        imagePullPolicy: IfNotPresent
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URI
          value: "postgresql://movie_db_username:movie_db_password@movie-db:5432/movie_db_dev"
        - name: CAST_SERVICE_HOST_URL
          value: "http://cast-service:8000/api/v1/casts/"