apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
spec:
  serviceName: movie-db
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: postgres
        image: postgres:12.1-alpine
        env:
        - name: POSTGRES_USER
          value: "movie_db_username"
        - name: POSTGRES_PASSWORD
          value: "movie_db_password"
        - name: POSTGRES_DB
          value: "movie_db_dev"
        volumeMounts:
        - name: movie-db-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: movie-db-storage
    spec:
      accessModes: [ "{{ .Values.postgres.accessMode }}" ]
      storageClassName: "{{ .Values.postgres.storageClass }}"
      resources:
        requests:
          storage: {{ .Values.postgres.storageSize }}