apiVersion: v1
kind: Service
metadata:
  name: movie-db
  labels:
    app: movie-db
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None    # headless for statefulset discovery (optional)
  selector:
    app: movie-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: movie-db
spec:
  serviceName: "movie-db"
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: postgres
        image: postgres:12.1-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          value: "movie_db_username"
        - name: POSTGRES_PASSWORD
          value: "movie_db_password"
        - name: POSTGRES_DB
          value: "movie_db_dev"
        volumeMounts:
        - name: movie-db-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: movie-db-storage
    spec:
      accessModes: ["ReadWriteOnce"]    # use ReadWriteMany if your storage supports it
      storageClassName: "rancher-default" # replace with correct storageclass name
      resources:
        requests:
          storage: 10Gi